name: fix-code-style using pint

on: push

jobs:
  pint:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}

      -   name: Install Composer
          run: composer install

      -   name: Run Laravel Pint
          run: ./vendor/bin/pint

      -   name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Apply laravel pint formatting